### ISSUE TITLE
Library version

### ISSUE THREAD

**Issue by adamvm** [DISTORTEC/lwIP-integration#1]
Hi, I was looking, but did not found which version of LwIP is integrated.

**Comment by FreddieChopin** [comment]
Current master. This repo should however work fine with any relatively recent lwIP 2.1 or maybe even 2.0.

**Comment by adamvm** [comment]
Looking at release and commit dates I would expect 2.0.2

**Comment by FreddieChopin** [comment]
http://git.savannah.nongnu.org/cgit/lwip.git
The last lwIP release is 2.1.2, which is 18 months old. The last release from 2.0 series is 2.0.3 which is 3 years old. Generally there should be almost zero integration-related-changes since lwIP 2.0.0, because the basic API should be compatible.

This repo works perfectly fine with the latest master, because this is what is used in https://github.com/DISTORTEC/STM32F7-ETH-LAN8720A-lwIP-MQTT
It also works fine with older versions of lwIP, which I used in some of my own projects.

**Comment by adamvm** [comment]
Thank you fo explanation
